# Generated by Django 5.2.17 on 2026-08-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_time', models.DateTimeField(db_index=True)),
                ('player_tag', models.CharField(db_index=True, max_length=255)),
                ('player_exp_lvl', models.IntegerField()),
                ('enemy_tag', models.CharField(max_length=255)),
                ('enemy_exp_lvl', models.IntegerField()),
                ('starting_trophies', models.IntegerField()),
                ('trophy_change', models.IntegerField()),
                ('raw_data', models.JSONField()),
            ],
            options={
                'db_table': 'crstats_battlelog',
                'ordering': ['-battle_time'],
                'indexes': [models.Index(fields=['player_tag', '-battle_time'], name='player_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('player_tag', 'battle_time'), name='unique_player_battle')],
            },
        ),
    ]
